### PR TITLE
feat: add function to map syscalls

### PR DESCRIPTION
**Pull request by algomaster99**
Todos
- [ ] allowlist.json should have CAPABILITIES written instead of syscalls
- [ ] write tests

### CODE REVIEW

**Comment by algomaster99** [comment]
@carminecesarano I will refer from [here](https://thevivekpandey.github.io/posts/2017-09-25-linux-system-calls.html) about the syscall numbers.
Also, we would use this mapping function to convert syscall from eBPF to capability. Ideally, `allowlist.json` should be entirely be created using `capslock` and we know it is not the case. Hence, we would add some capabilities manually using the same map function to augment it with more capabilities.

**Comment by carminecesarano** [comment]
@algomaster99 Another option to consider is modifying Capslock to return a list of individual invoked Go functions (e.g. os.ReadFile, os.WriteFile) rather than capabilities. We could then map these functions one to one to syscalls. This approach could enable more fine-grained enforcement, instead of applying controls to a group of syscalls (capability). 

For example, we might want our package to only read from the filesystem and not write, but Capslock groups both operations under CAPABILITY_FILES.

**Comment by algomaster99** [comment]
I would not prefer this approach because `capslock` already does a good job of identifying capabilities.What it lacks is that `CAPABILITY_CGO` is not fine-grained.
For example, if the allowlist from `capslock` is
```
{
    "dependencies": {
      "github.com/coredns/coredns/plugin/pkg/log": ["CAPABILITY_FILES", "CAPABILITY_CGO"],  
    }
  }
```
We should augment it to
```
{
    "dependencies": {
      "github.com/coredns/coredns/plugin/pkg/log": ["CAPABILITY_FILES", "CAPABILITY_READ_SYSTEM_STATE"], 
	// `READ_SYSTEM_STATE` would correspond to `get_pid` system call 
    }
  }
```

> os.ReadFile, os.WriteFile

there would be many more functions to map than capabilities so it might be easier.

**Comment by carminecesarano** [comment]
I agree, using capabilities is also easier and more understandable for developer than syscall allowlist. Similar to  `CAPABILITY_CGO`, we should refine capabilities like  `CAPABILITY_ARBITRARY_EXECUTION`, and  `CAPABILITY_EXEC`, which could hide arbitrary capabilities.

**Comment by algomaster99** [comment]
Let's work on merging #1 first.

**Pull request closed without merging**
